WITH CTE as (
select
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,
DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) AS DAYOFWEEK,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME,
CASE WHEN
DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN('Sat','Sun')
THEN 'Weekend'
ELSE 'Businessday' 
END as DAYTYPE,
MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_NR,
CASE WHEN
MONTH(TO_TIMESTAMP(STARTED_AT)) in (1,2,3)
THEN 'Winter'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (4,5,6)
THEN 'Spring'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (7,8,9)
THEN 'Summer'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (10,11,12)
THEN 'Autumn'
END as STATION_OF_YEAR
from {{ source('demo', 'BIKE') }}
where STARTED_AT !='started_at'
)

select * from CTE