WITH CTE as (
select
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,
DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) AS DAYOFWEEK,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME,

{{get_daytype('STARTED_AT')}} as DAY_TYPE,

MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_NR,

{{get_season('STARTED_AT')}} as STATION_OF_YEAR

from {{ source('demo', 'BIKE') }}
where STARTED_AT !='started_at'
)

SELECT * FROM CTE