{{ config(materialized='table') }}

WITH TRIPS as (

select
RIDE_ID
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) as TRIP_DATE,
START_STATION_ID,
END_STATION_ID,
MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

from
{{ source('demo', 'BIKE') }}


)
select * from TRIPS